### ISSUE TITLE
cielcleCIでECSに自動デプロイ

### ISSUE THREAD

**Issue by noguchidaisuke** [noguchidaisuke/gnavi#5]
前置き　[issueの書き方　参考にしたもの](https://qiita.com/awakia/items/c571e93e96a1ec28044f)

**Why**
---
デプロイ先をECSに変更したため、 circleCIでも設定を変更したい

**What**
--
- [ ] ECSインスタンス内でgit pull
- [ ] circleCI.ymlでimageをECRにpush
- [ ] ECSインスタンスないで新しいimageをpullしたのち、docker-compose buildを再度行う

**Comment by noguchidaisuke** [comment]
**Problem**
--
ecs-deployが通らない

**reason**
--
1.ALBを導入していいないためローリングアップデートの際にホストポート被って死ぬ
2.メモリをnginx-300 rails-300　と割り振っていたため、デプロイ時にt2microの制限メモリを超過指定た

**todo**
--
- [ ] サービスでALB定義。nginxのホストポート０に変更。
- [ ] nginx + rails container 合計メモリを500以下に調整

**Comment by noguchidaisuke** [comment]
Problem
----
deploy時にmigrateを実行したい。

todo
-----
- [ ] とりあえずrun-taskでcontaienrのcommandを書き換えてみる
- [ ] それがダメならecs-cli のservice-up試すかも
